# render.yaml
services:
  - type: web
    name: qine-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.efjlqddpxdclpoidqxmv:Qine-db%40123@aws-1-eu-central-2.pooler.supabase.com:6543/qine-db
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000